### PR TITLE
Release version 0.0.1 to staging

### PR DESCRIPTION
**Pull request by kicferk1**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by ethanmills** [comment]
Looks like the team-reviewers thing didn't work 😢

**Review by ethanmills — APPROVED** [review]
Ship it! 🚢🚢🚢

**Comment by kicferk1** [comment]
I would approve it, but it's using my token...

**Review by cfq — APPROVED** [review]

**Review by seb-siem-softwire — APPROVED** [review]
Yay!

**Review by amazimbe — APPROVED** [review]

**Pull request merged**
