### PR TITLE
ECF-RP-538: cip only schools

### PR DESCRIPTION
**Pull request by ethanmills**
### Context
Some schools are only eligible for the CIP. We'll deal with that properly later. For now, we just show them a special message when they try to trigger an email

### Changes proposed in this pull request
- Add `cip_only?` to `School`
- add guidance page to resend nomination journey for cip only schools

### Testing
- Edge case testing for eligibility on School
- Request specs for requesting invitation to nominate
- A11y and snapshot tests on new page

### Review Checks
- [x] All pages have automated accessibility checks via cypress
- [x] All pages have visual tests via cypress + percy
- [x] All `School` queries are correctly scoped - `eligible` when they need to be

### How can I view this in a review app?
https://ecf-review-pr-297.london.cloudapps.digital/nominations/choose-location
Try to resend and email to school with LA: "City of London", name: "City of London School for Girls" (type code 11)

### CODE REVIEW

**Comment by ethanmills** [comment]
['you're not quite eligible' screen for schools eligible for ECF but not for fip funding](https://trello.com/c/OM1BLT17/538-youre-not-quite-eligible-screen-for-schools-eligible-for-ecf-but-not-for-fip-funding)

**Review by kicferk1 — COMMENTED** [review]
Do we need to include some logic around that in the part of the app where we are letting induction coordinators choose between FIP and CIP materials? Is there a ticket for that?

**Comment by ethanmills** [comment]
> Do we need to include some logic around that in the part of the app where we are letting induction coordinators choose between FIP and CIP materials? Is there a ticket for that?

I don't think anyone has ever thought about that

**Comment by ethanmills** [comment]
I've raised that, and I expect it will be a new ticker

**Comment by ethanmills** [comment]
> Do we need to include some logic around that in the part of the app where we are letting induction coordinators choose between FIP and CIP materials? Is there a ticket for that?

I thought this comment was on a different review, and prompted a different question 😂 The ticket you're looking for is this one https://trello.com/c/50UK3rjp/528-school-not-eligible-for-dfe-funded-fip

**Review by kicferk1 — APPROVED** [review]

**Review by BroiSatse — APPROVED** [review]

**Review by goodviber — APPROVED** [review]
LGTM

**Pull request merged**
