### PR TITLE
Switch over validation to match against first name only

### PR DESCRIPTION
**Pull request by ethanmills**
Aim to boost automatic validation rate of mentors by only comparing their first name

### CODE REVIEW

**Review by kicferk1 — APPROVED** [review]
Looks like some tests are a touch fragile...

**Review by tonyheadford — COMMENTED** [review]
😬  I've just changed a whole load of this to cater for that in my PR

**Comment by ethanmills** [comment]
@tonyheadford how far off do you think yours is? Should I just wait for that?

**Comment by ethanmills** [comment]
I'm going to put this in for now @tonyheadford , shouldn't be too hard to undo

**Pull request merged**
