### PR TITLE
Run a rake task on an app in the dev space

### PR DESCRIPTION
**Pull request by ethanmills**
### Context
This should make it easier to run tasks in the dev cf space. I see this being used mostly for resetting the database on dev and review apps.

### CODE REVIEW

**Review by kicferk1 — APPROVED** [review]
Hmm, this might be a little late, given that we dispatch plenty of workflows already, but who can dispatch our workflows exactly? Repository admins? People with write access? I sure hope not everyone with read access :P

**Comment by cfq** [comment]
> Hmm, this might be a little late

You're right Michal, we might actually rethink our workflows after April. I need a quick way to reset a dev database right now.

**Comment by kicferk1** [comment]
> You're right Michal, we might actually rethink our workflows after April. I need a quick way to reset a dev database right now.

Hey, judging by teaching-vacancies repo, where I can't dispatch any workflows, it is pretty restricted. Soo, I think this is good to go. It's just that I haven't done much github actions before, and it's something that would be good to know :)

**Comment by ethanmills** [comment]
@kicferk1 Looks like everyone with write access https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event:~:text=GitHub%20Apps%20must%20have%20the%20actions%3Awrite%20permission%20to%20use%20this%20endpoint,-.%20For

**Pull request merged**
