### PR TITLE
Add lograge

### PR DESCRIPTION
**Pull request by ethanmills**
### Context
Rails currently gives three separate logs per request. This makes life very difficult. Lograge makes life easier again. 
Also both Teaching Vacancies AND Apply are doing it, so it must be a good idea!

### Guidance to review
Take a look at logit if you're curious, I recommend the following filter: `cf.app:"ecf-review-pr-164" and not cf_tags.source_type:"RTR"`

I've excluded /check logs, which I think is a good idea. Do you disagree?

### CODE REVIEW

**Review by kicferk1 — APPROVED** [review]
Soo, what are the differences in different environments? Just log level and whether we log sql? 

Round 2 of "wo de want some default environment config to commonize those things? (Not necessarily here, just in general)

Also, do we have a space somewhere to put some useful log queries? Like in our documentation, readme, confluence?

**Comment by ethanmills** [comment]
> Soo, what are the differences in different environments? Just log level and whether we log sql?

Deployed envs, yep pretty much

> Round 2 of "wo de want some default environment config to commonize those things? (Not necessarily here, just in general)

Quite possibly, Apply have something interesting for that

> Also, do we have a space somewhere to put some useful log queries? Like in our documentation, readme, confluence?

Not yet, I don't think we really know what's interesting yet

**Comment by amazimbe** [comment]
> > Do want some default environment config to commonize those things? (Not necessarily here, just in general)

In the past, I have always added common configs to environment.rb. However, the way our environment.rb looks seem to convey that the bolerplate did not recommend this. Are there any gov guidelines on this? What have other DfE projects done?

**Review by amazimbe — APPROVED** [review]
LGTM! We may need to discuss about where to put common configs but that doesn't need to block this.

**Pull request merged**
