### PR TITLE
ECF-1-419 Enhance choose-school auto complete

### PR DESCRIPTION
**Pull request by amazimbe**
### Context
We need to display the address as part of the select dropdown  so that users can narrow down their school with less ambiguity.

### Changes proposed in this pull request
Make the choose school dropdown look as in the attachment

### Testing
image

### Review Checks
- [x] All pages have automated accessibility checks via cypress
- [x] All `School` queries are correctly scoped - `eligible` when they need to be

### CODE REVIEW

**Comment by ethanmills** [comment]
Is accessible autocomplete failing the accessibility tests...?!

**Comment by amazimbe** [comment]
> Is accessible autocomplete failing the accessibility tests...?!

@ethanmills I think it's the <strong>name that I added that's causing it to fail matching

**Review by kicferk1 — APPROVED** [review]

**Comment by amazimbe** [comment]
[Changes to school search autocomplete in resend nomination flow](https://trello.com/c/vIDt0PVz/419-changes-to-school-search-autocomplete-in-resend-nomination-flow)

**Comment by ethanmills** [comment]
Not sure if it's an issue with our implementation or accessible autocomplete, but if you select an option then press backspace, you see this @amazimbe 
image

**Comment by ethanmills** [comment]
@amazimbe would you mind also updating the content per https://trello.com/c/vIDt0PVz/419-changes-to-school-search-autocomplete-in-resend-nomination-flow#action-60755ae39b15f405207c1400

Should be a one liner 🙂

**Comment by amazimbe** [comment]
> @amazimbe would you mind also updating the content per https://trello.com/c/vIDt0PVz/419-changes-to-school-search-autocomplete-in-resend-nomination-flow#action-60755ae39b15f405207c1400
> 
> Should be a one liner 🙂

Sure thing

**Comment by amazimbe** [comment]
> Not sure if it's an issue with our implementation or accessible autocomplete, but if you select an option then press backspace, you see this @amazimbe
> image

It's just the element background that was automatically set to transparent. Setting it to white should fix it. @ethanmills

**Review by ethanmills — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
