### PR TITLE
ECF-1-407 Adds tasks to school_cohorts plus refactoring

### PR DESCRIPTION
**Pull request by amazimbe**
### Changes proposed in this pull request
I've added a new model, task, that keeps track of what an induction tutor needs to do when they have selected the cip or the fip for their school. The rest is just refactoring. 
Screenshot 2021-03-31 at 23 39 02

### CODE REVIEW

**Comment by callumacrae** [comment]
This is great!

**Review by kicferk1 — COMMENTED** [review]
Is this a good idea? We will know whether the user completed those tasks through other things stored in the database. 

For example, we will know if user estimated how many ECTs and mentors because those values won't be null on a school cohort. We will know if they chose a provider, because that relationship will exist in our database.

And with this, we will need to worry about that data getting out of sync. Is this something we want to worry about?

**Comment by callumacrae** [comment]
> Is this a good idea? We will know whether the user completed those tasks through other things stored in the database.
> 
> For example, we will know if user estimated how many ECTs and mentors because those values won't be null on a school cohort. We will know if they chose a provider, because that relationship will exist in our database.
> 
> And with this, we will need to worry about that data getting out of sync. Is this something we want to worry about?

I thought about this a bit, but for stuff like accepting GDPR

**Comment by callumacrae** [comment]
sorry wrong button!

**Comment by amazimbe** [comment]
> Is this a good idea? We will know whether the user completed those tasks through other things stored in the database.
> 
> For example, we will know if user estimated how many ECTs and mentors because those values won't be null on a school cohort. We will know if they chose a provider, because that relationship will exist in our database.
> 
> And with this, we will need to worry about that data getting out of sync. Is this something we want to worry about?

Initially, I thought it was but I'm changing my mind. I'll release the pr that prompted this and then see if we need it or not. Probably just need methods but not schema. I'll put this on hold for now

**Pull request closed without merging**
