### PR TITLE
rm target _blank from link

### PR DESCRIPTION
**Pull request by goodviber**
### Context
Trello #515 - update links to guidance across the service so that they do NOT open in a new tab
### Changes proposed in this pull request
Update one link
### Guidance to review
Are there any more I have missed?
### Review Checks
- [ ] All pages have automated accessibility checks via cypress
- [ ] All `School` queries are correctly scoped - `eligible` when they need to be

### How can I view this in a review app?

### CODE REVIEW

**Comment by goodviber** [comment]
[Bug #13-15: update links to guidance across the service so that they do NOT open in a new tab](https://trello.com/c/0TDpfyWt/515-bug-13-15-update-links-to-guidance-across-the-service-so-that-they-do-not-open-in-a-new-tab)

**Review by amazimbe — APPROVED** [review]

**Comment by amazimbe** [comment]
@goodviber just noticed you need to resolve the conflicts

**Review by kicferk1 — COMMENTED** [review]
I think without `target _blank` we don't need `noopener noreferer`.

**Comment by kicferk1** [comment]
So is this a no-op now? 😢

**Pull request closed without merging**
