### PR TITLE
update ecf-govspeak version

### PR DESCRIPTION
**Pull request by xswoodsx**
### Context
Figures have been added to the latest ECF-govspeak.

### Changes proposed in this pull request
Bumping the ECF-govspeak version so that images will now be rendered in the app.

### Guidance to review

the below should output as shown in the picture
```
$Figure
$Alt Example of the part-whole model using the number 28. The number 20 has already been added to the lower left field, the lower right field is blank ready to be filled in. 
$EndAlt 
$URL https://www.early-career-framework.education.gov.uk/teachfirst/wp-content/uploads/sites/4/2020/08/Part-whole-model.jpg 
$EndURL 
$Caption Figure 1: Part-whole model. 
$EndCaption
$EndFigure
```

Screenshot 2021-01-14 at 11 39 03

### CODE REVIEW

**Review by amazimbe — APPROVED** [review]
LGTM!

**Comment by kicferk1** [comment]
I think the figcaption looks a bit weird - it's not centred under the image as I would expect.

We should probably double check govspeak handling of it, and bump this version if we find any bugs.

But other than that it looks great!

**Review by ethanmills — APPROVED** [review]
The caption still seems to be left aligned, and I'm a little surprised by the div class="img", but assuming that's all expected then this looks good 🙂

**Comment by kicferk1** [comment]
> The caption still seems to be left aligned, and I'm a little surprised by the div class="img", but assuming that's all expected then this looks good 🙂

Yeah, we copied the approach that govspeak takes with their other images, I hoped that in combination with govuk publishing components would center the caption, but oh well, I guess we will do it later in our app if we decide we want to.

**Review by kicferk1 — APPROVED** [review]

**Pull request merged**
