### PR TITLE
Touch User on update to participant profile

### PR DESCRIPTION
**Pull request by ethanmills**
The participants API uses updated_at on the User model

### CODE REVIEW

**Review by kicferk1 — APPROVED** [review]
Should we also touch `school_cohort` on the ecf participant profiles? So when induction programme choice changes (for example), we mark the participant as updated?

**Comment by kicferk1** [comment]
Argh, percy randomness strikes again 😢

**Comment by ethanmills** [comment]
> Argh, percy randomness strikes again 😢

I'll get it fixed separately 😢

**Comment by ethanmills** [comment]
We also need to do this for Partnerships and SchoolCohorts, but that will have to be callbacks I think. To be done separately

**Pull request merged**
