### PR TITLE
Erb guidance page for lead providers

### PR DESCRIPTION
**Pull request by mattonfoot**
### Context
Having two parallel ways of writing frontend code is a recipe for inconsistencies and developer frustration in the long run, not to mention added dependencies, testing questions, troubles integrating components, and so on.

It is not a good idea :/

It is as a massive tech-debt that we should not increase in the future.

### Changes proposed in this pull request
remove ability to use markdown and ERB to generate HTML web pages

### Guidance to review
Check the percy visual regression tests for consistency

### Testing
Cypres and Percy test that the content is visually the same

### CODE REVIEW

**Comment by mattonfoot** [comment]
This pull request should not be merged until https://github.com/DFE-Digital/early-careers-framework/pull/630 has been merged first

**Review by kicferk1 — APPROVED** [review]
Sweet.

**Comment by kicferk1** [comment]
```
  1) Lead Providers Partnership Management
       Learning how to manage partnerships:
     AssertionError: 2 accessibility violations were detected: expected 2 to equal 0
      at Context.eval (http://localhost:5017/__cypress/tests?p=cypress/support/index.js:34453:20)
```
is why cypress is unhappy :/

**Comment by kicferk1** [comment]
I would look at percy build, some interesting things in there.

Very good reasons to merge this PR too 😂

**Pull request merged**
