### PR TITLE
Fix cookie banner

### PR DESCRIPTION
**Pull request by callumacrae**
### Context

This was a bit of a nightmare to test due to differences between local and the dev environment, but I think I've got it!

I've also changed the tests so that they're more likely to catch failures—although it still doesn't catch the original problem.

### Guidance to review

This bug didn't happen on a PR environment last time either, so it's probably a code review only on this one…

### CODE REVIEW

**Review by kicferk1 — COMMENTED** [review]
So does the no-js version work on dev? Maybe reloading a page is not the end of the world?

**Review by ethanmills — APPROVED** [review]
How does this work for whoever you stole this from? Did they disable forgery protection for this?

**Comment by callumacrae** [comment]
> So does the no-js version work on dev? Maybe reloading a page is not the end of the world?

The no-js version worked all along, and now it's using all the form data not manually getting the bits I knew about, so this won't happen again, even if something changes in the way rails handles auth tokens in forms.

**Review by seb-siem-softwire — APPROVED** [review]

**Review by kicferk1 — APPROVED** [review]
So the long-term solution to prevent other devs falling into the same pit is "whenever you see a form submitted using manual javascript, make sure it sends all of form data"?

I guess we are re-doing a bunch of work that rails-ujs does (we cut it out because it didn't work well with rendering errors server-side). Maybe if it happens again we want to look into making a general solution work.

**Comment by callumacrae** [comment]
The long-term solution is to not develop your stuff in the test environment, because it disables the csrf protection 😆 

Yeah, it's pretty much just rails-ujs' `remote` behaviour. I don't see that it's something that will end up happening much in this project, but if it does an abtraction would be worth looking into.

**Pull request merged**
