### PR TITLE
Enqueue sign in emails to be delivered

### PR DESCRIPTION
**Pull request by jamesrose**
## Ticket and context

We can deliver these out of out-of-band. This will automatically give us [redelivery](https://sentry.io/organizations/dfe-bat/issues/2756441853/?environment=production&project=5748989&query=is%3Aunresolved) were Notify be down.

### CODE REVIEW

**Review by ethanmills — APPROVED** [review]
We need to be really careful to schedule all other emails with a lower priority

**Comment by ethanmills** [comment]
It might be good to have a lower default priority on the mailer queue, then set this higher e39504b0-9543-438a-aca3-b441c3b768bf

**Comment by tonyheadford** [comment]
> It might be good to have a lower default priority on the mailer queue, then set this higher https://github.com/collectiveidea/delayed_job#named-queues

Could we perhaps have a `priority_mailer` queue and lower the default on the mailer queue?

**Review by ethanmills — APPROVED** [review]
Looks good 🙂

**Pull request merged**
