### PR TITLE
CPDTP-170 Update API Sandbox landing page content

### PR DESCRIPTION
**Pull request by knowdigital**
### Context

https://dfedigital.atlassian.net/browse/CPDTP-170

### Changes proposed in this pull request

Selection_20210521-01-06b2106b2106b21

### Review Checks
- [ ] All pages have automated accessibility checks via cypress
- [ ] All pages have visual tests via cypress + percy
- [ ] All `School` queries are correctly scoped - `eligible` when they need to be

### CODE REVIEW

**Comment by timabell** [comment]
This replaces #402 and #403

**Review by timabell — CHANGES_REQUESTED** [review]
Rob I'm afraid you need to redo your commit from github desktop after setting your commit name

```
git show origin/update-sandbox-page
commit d50f0a510de65ea123e5b97acf6523d6b83d3f54 (origin/update-sandbox-page)
Author: rob <rob@Unknown.lan>
```

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

To redo the commit you need to "amend" the commit and the "force-with-lease" push the updated commit.

**Review by jamesrose — APPROVED** [review]

**Comment by timabell** [comment]
I've fixed up the author info for you to match the first commit you did @knowdigital

**Comment by timabell** [comment]
PR #405 will allow previewing the change if it's moved first

**Review by timabell — APPROVED** [review]

**Comment by timabell** [comment]
Preview here: https://ecf-review-pr-405.london.cloudapps.digital/sandbox while #405 is open

**Pull request merged**
